const fs = require('fs')
const path = require('path')

const packageJsonPath = path.resolve(__dirname, '..', 'package.json')
const versionFilePath = path.resolve(__dirname, '..', 'src', 'version.ts')

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'))

if (typeof packageJson.version !== 'string' || packageJson.version.length === 0) {
  throw new Error('package.json must contain a non-empty version string')
}

const contents = `// This file is generated by scripts/inject-version.cjs during build.\nexport const VERSION = ${JSON.stringify(packageJson.version)}\n`

fs.writeFileSync(versionFilePath, contents)
console.log(`Injected package version ${packageJson.version} into src/version.ts`)
